language: python
python:
  - "3.4"

# command to install dependencies (docs)
install: "pip install -q -r requirements.txt"

# command to run tests (docs)
script: sphinx-build -nW -b html -d doc/build/doctrees doc/source doc/build/html
